language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- pypy
- pypy3
- nightly
install:
- pip install -U requests[socks] bs4
- pip install coverage
script:
- coverage run test.py
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - secure: EAplG1sqHzMvKYYgy0MiKHsa+BMPWSte6C7bFHyInOlJ2y+PpaecN77pduFCkKDtHc2opKznzu4CpjFwc096GI0uuX47NkAzUdSgJ93JhDM2bBCO2Do+nnF+7d9stsTNA4g4zpN1hYOD+lp6r7HoHv8m4S9W6R8xzIU19EEiNeK0+y09Y79LtsyaYVHel8bCvH/ZC23OiiUD71p8bodkWgpmMlx8gkUmlJ9v7AdsWfdHhwi6Xx+WdblwmJtWWJlaMT7+LEC6VkJ4KnB9v+lsCHISWrXilvTnSVSrPHWgGs+rIJ9Ge6CCDHxmGHxYfTOnGn1sfvwqeh+zyCqv5theuGokl7h6iTZzU36+aL+2kPZmji4szLMDJrgj6Sjvn240wYUYJwqxOSU7FZYKZd7N7+miVFlZYnWPuKIk4goMTbDR6CJwyDuWk8iQ9oyL93/HIzm76zHkNN4KAYiQszpeanG/XeGRCPM3cLySiGlJ97LDhA/AQdq65zTPOJGXQYnNAQYDa8uYpU+WIxhoLwLixaR5B00X0Ie0xO4OvMHHp5binuJN3Mxl3uQ5WtXpmLjyxYvQUgl5bsYo3DrqpIgIGo1E8KZVAIUrg0Y4c5ZllS5avk46ooliex9cyQr5NX7h+A6SqLra0L1n5pnZSKLahbMciStrj28zIV3BEknTaTQ=
  - secure: PX7A7LI0vLvGWZ9sjnOHHzU2HScm7VnqX+svYKJC3Fxi9wmM4hc3zcI3wJP/kfWR77aWUQxZdW7sMLR7AD/fJAaVA19MNRQB4nUf4Q6gMHh0kmGtgm4reJ4HI4CpdMqbLtqMbWmEHwrdJujnin3Rk5XvnoSCpdguz63tzlls7f711ixP5Sgll8GfB4XB0Epw9GJkk1VQN/CJfCB7UAKrF22DSPApBSC8vvgxrtzPRLtP9C16LwmoAoIdC97ioSdlZqFMADjTVa2KK1+11GntntheoklSWmRT4QeATX1ywJEVEnHIalmbbbcEUPZ6zrv9elbMDXmUAQSWwh9L25u2dAP9YzY0JgpHcZxfekIifj3HNmwOO5YIO2VlD110aVJWruRA7+uIWY6FMlcYNd6RhQmNRroreQoMKT3HvHJZ3dFCdpqFJtryp7kby0Fd8QDFPrgZ1KiB7AZsEB+wUAeMasCe7LGlqq37TIOeiheyqAzhC8whGuHb7Kq+Bqqm9zY3EPpL3MSDDbPoRnY6Xn4z3HKVknEgu7E+bXOSMkJiXHxpxjK/aQI4aKCjjgc4fV8hV49EgL9G7S84fdULqcXa0rYZAENEzjLYXSY3kLqZuC/O6gu/Gk1N1PPkMP1BOrYbR9Sf273reVIejKwqIR30v3anDauE0X7NfRn349HCf/k=
  - PYTHONIOENCODING: utf8